export const Questions4 = [
  {
    id: 49,
    que: "Rate your satisfaction with the choice of your career",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 50,
    que: "Rate your satisfaction with your present job/business/school",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 51,
    que: "Rate your satisfaction with your capacity to have fun",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 52,
    que: "Rate your satisfaction with the amount of fun experienced in last month ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 53,
    que: "Rate your satisfaction with your financial prospects",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 54,
    que: "Rate your satisfaction with your current income level",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 55,
    que: "Rate your satisfaction with your level of self-esteem",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 56,
    que: "Rate your satisfaction with the prospects for having impact on those who know you and possibly others",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 57,
    que: "Rate your satisfaction with your sex life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 58,
    que: "Rate your satisfaction with your body, how it looks and performs",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 59,
    que: "Rate your satisfaction with your home life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 60,
    que: "Rate your satisfaction with your life skills and knowledge of issues and facts unrelated to your job or profession",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 61,
    que: "Rate your satisfaction with your stress management capacities",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 62,
    que: "Rate your satisfaction with your nutritional knowledge, attitudes, and choices ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 63,
    que: "Rate your satisfaction with your ability to recover from disappointment, hurts, setbacks, and tragedies",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 64,
    que: "Rate your satisfaction with your confidence that you currently are, or will in the future be, reasonably close to your highest potential",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 65,
    que: "Rate your satisfaction with your achievement of a rounded or balanced quality in your life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 66,
    que: "Rate your satisfaction with your sense that life for you is on an upward curve, getting better and fuller all the time",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 67,
    que: "Rate your satisfaction with your level of participation in issues and concerns beyond your immediate interests",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 68,
    que: "Rate your satisfaction with your choice whether to parent or not and with the consequences or results of that choice",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 69,
    que: "Rate your satisfaction with your Emotional acceptance of the inescapable reality of aging",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
];
