export const Questions2 = [
  {
    id: 20,
    que: "To what extent do you believe that you have a history of coping well with highly stressful situations?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 21,
    que: "How confident are you of being able to control your emotions in stressful situations?",
    op1: "I never let my emotions run away me",
    op2: "I seldom let my emotions run away me",
    op3: "I sometimes let my emotions run away me",
    op4: "I often let my emotions run away me",
    op5: "I cannot control my emotions at all in stressful situations",
  },
  {
    id: 22,
    que: "When things are not going well, how likely are you to view the situation as being temporary rather than permanent?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 23,
    que: "When something bad happens to you, how likely are you to exaggerate its importance?",
    op1: "Very unlikely",
    op2: "Unlikely",
    op3: "Likely",
    op4: "Very likely",
    op5: "Most likely",
  },
  {
    id: 24,
    que: "When stressed by a complex situation, how likely are you to focus your attention on those aspects of the situation that you can manage?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 25,
    que: "When highly stressed, how capable are you of changing your thinking to calm down?",
    op1: "Most capable",
    op2: "Very capable",
    op3: "Capable",
    op4: "Incapable",
    op5: "Very incapable",
  },
  {
    id: 26,
    que: "To what extent are you aware of practical, healthy ways of relaxing?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 27,
    que: "How frequently do you pursue some highly relaxing practice?",
    op1: "Daily or more often",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
  },
  {
    id: 28,
    que: "When confronted with a stressful situation, how likely are you to wait passively for events to develop rather than to take charge?",
    op1: "Very unlikely",
    op2: "Unlikely",
    op3: "Likely",
    op4: "Very likely",
    op5: "Most likely",
  },
  {
    id: 29,
    que: "Which of the following courses of action are you most likely to take when you have become thoroughly frustrated?",
    op1: "Identify an alternate goal and pursue it",
    op2: "Pursue a relaxing activity",
    op3: "Withdraw and feel sorry for yourself",
    op4: "Vent your aggression on someone weaker than you",
    op5: "Shout, threaten and bombard someone with hostile s",
  },
  {
    id: 30,
    que: "If you had worn an article of clothing one day and then found it to be flawed, how likely would you be to return it and ask for a refund?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 31,
    que: "When an unexpected, negative event happens to you, how likely are you to actively seek information about the event and how to cope with it?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 32,
    que: "How much decision-making power so you have in your family?",
    op1: "More power than any other member of my family",
    op2: "As much power as any other member of my family",
    op3: "Less power than some members of my family",
    op4: "Less power than most members of my family",
    op5: "Less power than any members of my family",
  },
  {
    id: 33,
    que: "How much decision-making power do you have in your working environment?",
    op1: "More power than any other member of my work team",
    op2: "As much power as any other member of my work team",
    op3: "Less power than some members of my work team",
    op4: "Less power than most members of my work team",
    op5: "Less power than any members of my work team",
  },
  {
    id: 34,
    que: "To what extent do you believe that events in your life are merely the result of luck, fate, or chance?",
    op1: "To a very little extent",
    op2: "To a little extent",
    op3: "To some extent",
    op4: "To a good extent",
    op5: "To a very great extent",
  },
];
