export const Questions1 = [
  {
    id: 1,
    que: "How often do you experience headaches?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 2,
    que: "How often do you experience tense muscles, sore back and neck?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 3,
    que: "How often do you experience fatigue?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 4,
    que: "How often do you experience anxiety, worry or phobias?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 5,
    que: "How often do you experience difficulty falling asleep?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 6,
    que: "How often do you experience irritability?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 7,
    que: "How often do you experience insomnia?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 8,
    que: "How often do you experience bouts of anger/hostility?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 9,
    que: "How often do you experience boredom or depression?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 10,
    que: "How often do you eat too much or too little?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 11,
    que: "How often do you experience diarrhea, cramps, gas or constipation?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 12,
    que: "How often do you experience restlessness, itching or tics?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 13,
    que: "How frequently do you moderately exercise?",
    op1: "Daily",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
  },
  {
    id: 14,
    que: "How often do you get a full, restful night of sleep?",
    op1: "Almost every night",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
  },
  {
    id: 15,
    que: "To what extent is your energy sufficient for your work and daily activities?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 16,
    que: "How closely does your weight approach the ideal level?",
    op1: "My weight is at the ideal level",
    op2: "My weight is almost close to the ideal level",
    op3: "My weight is close to the ideal level",
    op4: "My weight is not close to the ideal level",
    op5: "I am dangerously overweight/ underweight",
  },
  {
    id: 17,
    que: "To what extent do you eat a nutritious diet?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 18,
    que: "Which of the following best describes your use of tobacco?",
    op1: "In no period of my life have I had the habit of smoking or chewing tobacco",
    op2: "Early in my life for a short period I smoked or chewed tobacco",
    op3: "I stopped smoking or chewing tobacco over the past two years",
    op4: "I smoke or chew tobacco fairly often",
    op5: "I smoke or chew tobacco almost everyday",
  },
  {
    id: 19,
    que: "Which of the following best describes your use of alcohol?",
    op1: "I do not abuse alcohol, and never have",
    op2: "Very occasionally I abuse alcohol",
    op3: "I have a history of abusing alcohol, but am not presently abusing it",
    op4: "I abuse alcohol whenever I feel sad or depressed",
    op5: "I abuse alcohol almost daily",
  },
  {
    id: 20,
    que: "To what extent do you believe that you have a history of coping well with highly stressful situations?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 21,
    que: "How confident are you of being able to control your emotions in stressful situations?",
    op1: "I never let my emotions run away me",
    op2: "I seldom let my emotions run away me",
    op3: "I sometimes let my emotions run away me",
    op4: "I often let my emotions run away me",
    op5: "I cannot control my emotions at all in stressful situations",
  },
  {
    id: 22,
    que: "When things are not going well, how likely are you to view the situation as being temporary rather than permanent?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 23,
    que: "When something bad happens to you, how likely are you to exaggerate its importance?",
    op1: "Very unlikely",
    op2: "Unlikely",
    op3: "Likely",
    op4: "Very likely",
    op5: "Most likely",
  },
  {
    id: 24,
    que: "When stressed by a complex situation, how likely are you to focus your attention on those aspects of the situation that you can manage?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 25,
    que: "When highly stressed, how capable are you of changing your thinking to calm down?",
    op1: "Most capable",
    op2: "Very capable",
    op3: "Capable",
    op4: "Incapable",
    op5: "Very incapable",
  },
  {
    id: 26,
    que: "To what extent are you aware of practical, healthy ways of relaxing?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 27,
    que: "How frequently do you pursue some highly relaxing practice?",
    op1: "Daily or more often",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
  },
  {
    id: 28,
    que: "When confronted with a stressful situation, how likely are you to wait passively for events to develop rather than to take charge?",
    op1: "Very unlikely",
    op2: "Unlikely",
    op3: "Likely",
    op4: "Very likely",
    op5: "Most likely",
  },
  {
    id: 29,
    que: "Which of the following courses of action are you most likely to take when you have become thoroughly frustrated?",
    op1: "Identify an alternate goal and pursue it",
    op2: "Pursue a relaxing activity",
    op3: "Withdraw and feel sorry for yourself",
    op4: "Vent your aggression on someone weaker than you",
    op5: "Shout, threaten and bombard someone with hostile s",
  },
  {
    id: 30,
    que: "If you had worn an article of clothing one day and then found it to be flawed, how likely would you be to return it and ask for a refund?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 31,
    que: "When an unexpected, negative event happens to you, how likely are you to actively seek information about the event and how to cope with it?",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 32,
    que: "How much decision-making power so you have in your family?",
    op1: "More power than any other member of my family",
    op2: "As much power as any other member of my family",
    op3: "Less power than some members of my family",
    op4: "Less power than most members of my family",
    op5: "Less power than any members of my family",
  },
  {
    id: 33,
    que: "How much decision-making power do you have in your working environment?",
    op1: "More power than any other member of my work team",
    op2: "As much power as any other member of my work team",
    op3: "Less power than some members of my work team",
    op4: "Less power than most members of my work team",
    op5: "Less power than any members of my work team",
  },
  {
    id: 34,
    que: "To what extent do you believe that events in your life are merely the result of luck, fate, or chance?",
    op1: "To a very little extent",
    op2: "To a little extent",
    op3: "To some extent",
    op4: "To a good extent",
    op5: "To a very great extent",
  },
  {
    id: 35,
    que: "What is your best guess as to the extent and quality of contact you had with your parent(s) shortly after birth?",
    op1: "Was given an above average amount of contact by happy parent",
    op2: "Was given an average amount of contact by happy parent",
    op3: "Was given an average amount of contact by unhappy (perhaps angry) parent(s)",
    op4: "Was given a below average amount of contact by unhappy (perhaps angry) parent(s)",
    op5: "Was given the least amount of contact by unhappy (perhaps angry) parent(s)",
  },
  {
    id: 36,
    que: "During your early childhood, to what extent was your mother both calm and generally permissive?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 37,
    que: "How easily do you make friends in a strange situation?",
    op1: "Very easily",
    op2: "Fairly easily",
    op3: "Easily",
    op4: "Uneasily",
    op5: "Very uneasily",
  },
  {
    id: 38,
    que: "When highly stressed, how likely are you to ask friends or relatives for help? ",
    op1: "Most likely",
    op2: "Very likely",
    op3: "Likely",
    op4: "Unlikely",
    op5: "Very unlikely",
  },
  {
    id: 39,
    que: "In comparison with other people, how likely are you to see others as threatening, uncooperative, or exploitative?",
    op1: "Highly unlikely",
    op2: "Very unlikely",
    op3: "Unlikely",
    op4: "Very likely",
    op5: "Highly likely",
  },
  {
    id: 40,
    que: "How often are you confused about the intentions of others toward you?",
    op1: "Very infrequently",
    op2: "Infrequently",
    op3: "Frequently",
    op4: "Very frequently",
    op5: "Almost always",
  },
  {
    id: 41,
    que: "Rate your satisfaction with your role in some kind of network of friends, relatives, and/or others about whom you care deeply and who reciprocate that commitment to you",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 42,
    que: "Rate your satisfaction with your marital status",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 43,
    que: "Rate your satisfaction with your primary relationships",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 44,
    que: "How often do you engage in a spiritual practice such as prayer, mediation, or inspirational reading to enrich your interior life?",
    op1: "Daily or more often",
    op2: "3-4 times per week",
    op3: "Once or twice a week",
    op4: "Once or twice a month",
    op5: "Seldom",
  },
  {
    id: 45,
    que: "How connected do you feel to your conception of a higher power or to a worthy cause?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 46,
    que: "To what extent do you believe your life has purpose?",
    op1: "To a very great extent",
    op2: "To a good extent",
    op3: "To some extent",
    op4: "To a little extent",
    op5: "To a very little extent",
  },
  {
    id: 47,
    que: "How much contact do you have with what you would consider a spiritual community?",
    op1: "Very much",
    op2: "Fairly much",
    op3: "Not very much",
    op4: "Little",
    op5: "Very little",
  },
  {
    id: 48,
    que: "Rate your satisfaction with your spirituality",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 49,
    que: "Rate your satisfaction with the choice of your career",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 50,
    que: "Rate your satisfaction with your present job/business/school",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 51,
    que: "Rate your satisfaction with your capacity to have fun",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 52,
    que: "Rate your satisfaction with the amount of fun experienced in last month ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 53,
    que: "Rate your satisfaction with your financial prospects",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 54,
    que: "Rate your satisfaction with your current income level",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 55,
    que: "Rate your satisfaction with your level of self-esteem",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 56,
    que: "Rate your satisfaction with the prospects for having impact on those who know you and possibly others",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 57,
    que: "Rate your satisfaction with your sex life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 58,
    que: "Rate your satisfaction with your body, how it looks and performs",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 59,
    que: "Rate your satisfaction with your home life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 60,
    que: "Rate your satisfaction with your life skills and knowledge of issues and facts unrelated to your job or profession",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 61,
    que: "Rate your satisfaction with your stress management capacities",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 62,
    que: "Rate your satisfaction with your nutritional knowledge, attitudes, and choices ",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 63,
    que: "Rate your satisfaction with your ability to recover from disappointment, hurts, setbacks, and tragedies",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 64,
    que: "Rate your satisfaction with your confidence that you currently are, or will in the future be, reasonably close to your highest potential",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 65,
    que: "Rate your satisfaction with your achievement of a rounded or balanced quality in your life",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 66,
    que: "Rate your satisfaction with your sense that life for you is on an upward curve, getting better and fuller all the time",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 67,
    que: "Rate your satisfaction with your level of participation in issues and concerns beyond your immediate interests",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 68,
    que: "Rate your satisfaction with your choice whether to parent or not and with the consequences or results of that choice",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 69,
    que: "Rate your satisfaction with your Emotional acceptance of the inescapable reality of aging",
    op1: "Very happy",
    op2: "Mildly happy",
    op3: "Mildly disappointed",
    op4: "Very disappointed",
    op5: "Completely disappointed",
  },
  {
    id: 70,
    que: "In the last week, how often have you been upset because of something that happened unexpectedly?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
  {
    id: 71,
    que: "In the last week, how often have you felt that you were unable to control important things in your life?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
  {
    id: 72,
    que: "In the last week, how often have you felt nervous and 'stressed'?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
  {
    id: 73,
    que: "In the last week, how often have you felt confident about your ability to handle your personal problems?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
  },
  {
    id: 74,
    que: "In the last week, how often have you felt that things were going your way?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
  },
  {
    id: 75,
    que: "In the last week, how often have you found that you could NOT cope with all the things you had to do?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
  {
    id: 76,
    que: "In the last week, how often have you been able to control irritations in your life?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
  },
  {
    id: 77,
    que: "In the last week, how often have you felt that you were on top of things?",
    op1: "Very Often",
    op2: "Fairly Often",
    op3: "Sometimes",
    op4: "Almost Never",
    op5: "Never",
  },
  {
    id: 78,
    que: "In the last week, how often have you been angered because of things that happened that were out of your control?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
  {
    id: 79,
    que: "In the last week, how often have you felt difficulties were piling up so high that you could not overcome them?",
    op1: "Never",
    op2: "Almost Never",
    op3: "Sometimes",
    op4: "Fairly Often",
    op5: "Very Often",
  },
];
