export const Questions = [
  {
    id: 1,
    que: "How often do you experience headaches?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 2,
    que: "How often do you experience tense muscles, sore back and neck?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 3,
    que: "How often do you experience fatigue?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 4,
    que: "How often do you experience anxiety, worry or phobias?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 5,
    que: "How often do you experience difficulty falling asleep?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 6,
    que: "How often do you experience irritability?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 7,
    que: "How often do you experience insomnia?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 8,
    que: "How often do you experience bouts of anger/hostility?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 9,
    que: "How often do you experience boredom or depression?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 10,
    que: "How often do you eat too much or too little?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 11,
    que: "How often do you experience diarrhea, cramps, gas or constipation?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
  {
    id: 12,
    que: "How often do you experience restlessness, itching or tics?",
    op1: "Never",
    op2: "Once or twice a month",
    op3: "Once a week",
    op4: "2-3 times per week",
    op5: "Almost everyday",
  },
];
